### ISSUE TITLE
Please remove reference to Cupertino Icon.

### ISSUE THREAD

**Issue by awazgyawali** [IronLad85/flutter_calendar_strip#11]
https://github.com/IronLad85/flutter_calendar_strip/blob/30387e923090a36e80dda3baafa8acc2a1d08f32/lib/calendar_strip.dart#L260

This reference is causing some invalid rendering on some devices. Please give a parameter to override the icon or add icon from the material package.

**Comment by cimplesid** [comment]
@awazgyawali @IronLad85 [pullreq13](https://github.com/IronLad85/flutter_calendar_strip/pull/13) this pr solves the issue

**Comment by IronLad85** [comment]
Pull Request "pullreq13"  merged now

**Comment by IronLad85** [comment]
Pull Request "pullreq13" merged now
