### ISSUE TITLE
exception when dispose

### ISSUE THREAD

**Issue by tremp-m** [IronLad85/flutter_calendar_strip#15]
if init animation is runing and dispose called - execption will be throwing:

> I/zygote  (14401): After code cache collection, code=101KB, data=57KB
I/zygote  (14401): Do partial code cache collection, code=102KB, data=60KB
I/zygote  (14401): After code cache collection, code=102KB, data=60KB
I/zygote  (14401): Increasing code cache capacity to 512KB

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
SlideFadeTransitionState#c8385(tickers: tracking 1 ticker) was disposed with an active Ticker.

SlideFadeTransitionState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by SlideFadeTransitionState#c8385(lifecycle state: created, tickers: tracking 0 tickers))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:66:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:68:6)
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:237:80)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:168:34)
#4      new AnimationController (package:flutter/src/animation/animation_controller.dart:245:21)
#5      SlideFadeTransitionState.initState (package:calendar_strip/calendar_strip.dart:386:23)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#14     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#16     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#23     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
....
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#204    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#205    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#209    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#210    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#211    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#212    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#213    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#214    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#218    _invoke (dart:ui/hooks.dart:259:10)
#219    _drawFrame (dart:ui/hooks.dart:217:3)
(elided 3 frames from package dart:async)

When the exception was thrown, this was the stack: 
#0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:185:13)
#1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:203:6)
#2      SlideFadeTransitionState.dispose (package:calendar_strip/calendar_strip.dart:420:11)
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4435:12)
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1748:13)
...

> 
i fix it:

```
class SlideFadeTransitionState extends State<SlideFadeTransition> with TickerProviderStateMixin {
  AnimationController _animController;
  Animation<Offset> _animOffset;
  bool _disposed=false;
.....
if(!_disposed) _animController.forward();
...


@override
  void dispose() {
    _disposed = true;
    _animController.dispose();
    super.dispose();
  }
```

**Comment by arbpsc** [comment]
I came into the same problem, I have a menu tab and it will try to dispose but the animation is ongoing, I think ou only need to change the order of the dispose, dispose the controller first.

**Comment by tremp-m** [comment]
it's first what i made, but got another exception... "_disposed " - help with it.... (maybe second exception have another fix.... - I did not deal with it for a long time)

**Comment by IronLad85** [comment]
I have been busy on other work, I'm gonna check this issue soon as possible. Meanwhile if you guys have found any solution, feel free to open a pull request
