### ISSUE TITLE
SlideFadeTransitionState Error

### ISSUE THREAD

**Issue by usescrt** [IronLad85/flutter_calendar_strip#19]
Hi,

I get an error if I change the page before the animation is complete.

`════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
SlideFadeTransitionState#ddfd7(tickers: tracking 1 ticker) was disposed with an active Ticker.

SlideFadeTransitionState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was: _WidgetTicker(created by SlideFadeTransitionState#ddfd7(lifecycle state: created, tickers: tracking 0 tickers))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> 
package:flutter/…/scheduler/ticker.dart:66
#1      new Ticker 
package:flutter/…/scheduler/ticker.dart:68
#2      new _WidgetTicker
#3      TickerProviderStateMixin.createTicker 
package:flutter/…/widgets/ticker_provider.dart:202
#4      new AnimationController 
package:flutter/…/animation/animation_controller.dart:247
#5      SlideFadeTransitionState.initState 
package:calendar_strip/calendar_strip.dart:385
#6      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4640
#7      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4476
...     Normal element mounting (7 frames)
#14     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
#15     MultiChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5947
...     Normal element mounting (7 frames)
#22     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
#23     MultiChildRenderObjectElement.mount 
package:flutter/…/wi`

**Comment by IronLad85** [comment]
Okay let me look at that bug. Will fix asap

**Comment by gullskatten** [comment]
@IronLad85  Viewing the code of version `1.0.6` of calendar_strip it seems that `super.dispose()` is called before the `_animController.dispose()`, causing the error. Viewing the code on the `master` branch however, this seems to be fixed - not sure if the current master-version code has been released?

```
 @override
  void dispose() {
    super.dispose();
    _animController.dispose(); // this should be called before super.dispose();
  }
```
