### ISSUE TITLE
Add possibility to set endDate as selectedDate

### ISSUE THREAD

**Issue by Schokohuetchen** [IronLad85/flutter_calendar_strip#2]
I'm trying to create a calendar strip for a time-tracking system. The user isn't supposed to be able to go back more than seven days or access any days after the current day. When the app is opened, I'd like the current day(= endDate) to be pre-selected.

![image](https://user-images.githubusercontent.com/15674036/74445000-fa8e6e80-4e75-11ea-8537-a1699d8bea65.png)

However, this is impossible since the widget doesn't recognise same dates as such. This code always returns true...

![image](https://user-images.githubusercontent.com/15674036/74445230-56f18e00-4e76-11ea-828c-3f9598359b3f.png)

...which causes the currentDate to be set to the startDate. 
![image](https://user-images.githubusercontent.com/15674036/74445339-87392c80-4e76-11ea-90b3-b49663c5d1b4.png)

I'd like to be able to set the selectedDate to the endDate of a date range, even if the endDate is the current date.

**Comment by IronLad85** [comment]
> I'm trying to create a calendar strip for a time-tracking system. The user isn't supposed to be able to go back more than seven days or access any days after the current day. When the app is opened, I'd like the current day(= endDate) to be pre-selected.
> 
> ![image](https://user-images.githubusercontent.com/15674036/74445000-fa8e6e80-4e75-11ea-8537-a1699d8bea65.png)
> 
> However, this is impossible since the widget doesn't recognise same dates as such. This code always returns true...
> 
> ![image](https://user-images.githubusercontent.com/15674036/74445230-56f18e00-4e76-11ea-828c-3f9598359b3f.png)
> 
> ...which causes the currentDate to be set to the startDate.
> ![image](https://user-images.githubusercontent.com/15674036/74445339-87392c80-4e76-11ea-90b3-b49663c5d1b4.png)
> 
> I'd like to be able to set the selectedDate to the endDate of a date range, even if the endDate is the current date.

Did u try to make use of "selectedDate" by setting it to the endDate which you have now ?

**Comment by IronLad85** [comment]
@Schokohuetchen Hi, Did u make use of "selectedDate" by setting it to the endDate you have ?

**Comment by Schokohuetchen** [comment]
Yes, but since the endDate is always the currentDate, the problem persists. If you don't set the selectedDate, the selectedDate is set to the current date by default. The problem is the return value of _isDateAfter_: 

If endDate is set to DateTime.now(), !currentDate.isBefore(endDate) will always return true since both dates are equal. So neither can be before or after the other. So this still results in the currentDate to be set to the startDate.

**Comment by IronLad85** [comment]
Oh okay got it. I used a temporary workaround during development and didn't fix it later. I am gonna push a fix to that soon. If you have already found a fix, you are welcome to make a pull request.

**Comment by IronLad85** [comment]
I have made the bug fix and updated the code. Now you can set endDate as selectedDate
