### ISSUE TITLE
Two days have same number date, Help me please.

### ISSUE THREAD

**Issue by federico2390** [IronLad85/flutter_calendar_strip#29]
The 25 October 2020 is Sunday but, if I go to next days, Monday, is ever 25 as number... Why? Please help me how can I solve this... 
![Simulator Screen Shot - iPhone 11 - 2020-10-20 at 00 53 58](https://user-images.githubusercontent.com/42987961/96520153-c2de8e80-126e-11eb-8d21-5e67bebde143.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-20 at 00 54 01](https://user-images.githubusercontent.com/42987961/96520156-c40fbb80-126e-11eb-8887-953b63f75d6f.png)

**Comment by RobbeDGreef** [comment]
This is due to Dart's daylight saving system, I've noticed too and already created a pull request that fixes the issue. We just have to wait for the creator to merge it (if he wants to). If it is very urgent you can use my fixed branch https://github.com/RobbeDGreef/flutter_calendar_strip/tree/utcTimeFix

**Comment by federico2390** [comment]
Ok but what i need to overwrite?

**Comment by RobbeDGreef** [comment]
I think the best you can do is clone my fork and copy the contents of the lib/ directory into a folder called calendar_strip in the lib/ folder of your own project (you have to create this calendar_strip folder yourself). And then change your includes from `import "package:calendar_strip/calendar_strip.dart"` to `import "calendar_strip/calendar_strip.dart"`.

**Comment by IronLad85** [comment]
@RobbeDGreef  Your pull request with the fix has been merged and publish. Thanks for the contribution to this library. 👍  :)
