### ISSUE TITLE
Is it possible to dynamically set a selected date?

### ISSUE THREAD

**Issue by watsmyname** [IronLad85/flutter_calendar_strip#5]
Is there any way to select the date dynamically? Like click a button and and select a date.

**Comment by IronLad85** [comment]
Did you mean to change  selected date dynamically after some button click action from user ?

**Comment by watsmyname** [comment]
> Did you mean to change selected date dynamically after some button click action from user ?

Yes that is exactly what I meant. And this will make this good package more extendable. Because we could make it work easily when there is datepicker widget as well.

**Comment by IronLad85** [comment]
That functionality isn't currently added yet. I am going to add it in the next update soon.
