### ISSUE TITLE
Set start of week to Sunday not Monday

### ISSUE THREAD

**Issue by AdamBCo** [IronLad85/flutter_calendar_strip#8]
Is it possible to set the start of the week to Sunday as opposed to Monday?

If so, how can I achieve that?

**Comment by watsmyname** [comment]
I have added an option to set Sunday as the first day of a week. I have made a pull request, hopefully developer will merge and release an update soon

**Comment by IronLad85** [comment]
Merged the pull request from @watsmyname . Thanks for the contribution
